### ISSUE TITLE
webpack compatibility

### ISSUE THREAD

**Issue by revolunet** [gre/kenburns-webgl#1]
Hey, i have an unknown issue when using webpack to build a `diaporama-react`  demo :

```sh
ERROR in ./~/kenburns-webgl/src/index.js
Module not found: Error: Cannot resolve module 'glslify' in /Users/juju/Documents/projects/diaporama1/node_modules/kenburns-webgl/src
 @ ./~/kenburns-webgl/src/index.js 1:14-32
webpack: bundle is now VALID.
```

any idea what could go wrong ?

**Comment by gre** [comment]
oh yeah, I guess kenburns-webgl is currently not working for webpack because it uses glslify ( https://github.com/stackgl/glslify ) which is a browserify transform.

I'm not sure how to solve this.
cc @mattdesl: any idea? I've noticed there is also https://github.com/stackgl/glslify-loader but it doesn't have the same API. Is the (only) solution to publish pre-compiled package? Thanks

**Comment by revolunet** [comment]
Thanks

there's https://www.npmjs.com/package/webpack-package-loaders-plugin that allow to define webpack config in package.json as you do with browserify.
but couldnt make it work for some reason

**Comment by gre** [comment]
the APIs of glslify and glslify-loader are different. I guess I should just publish a compiled bundle to NPM

**Comment by revolunet** [comment]
yes please :)

**Comment by mattdesl** [comment]
Bundling is not a good solution since it will include all your dependencies (in this case gl-shader). This means that this module will always lag behind patches to gl-shader, and will cause more duplication in people's final bundles. 

An ideal approach would be transpiration with a Babel plugin for glslify, but this doesn't exist yet. 

A stop gap solution for the time being is to use this loader. I haven't tested with glslify, though. 

https://github.com/webpack/transform-loader/

**Comment by mattdesl** [comment]
Another temporary fix is to write a "webpack.js" entry point that can be required directly. Kinda ugly.

**Comment by gre** [comment]
Thanks @mattdesl ,
for now I will probably just remove the glslify dep (for this specific tiny module), but the question remain, probably we'll need to make a "universal" glslify as you said. :)

**Comment by gre** [comment]
v2.0.1

**Comment by revolunet** [comment]
Thanks a lot :+1:

**Comment by mattdesl** [comment]
Ah yes that is the easiest solution for sure. 😆👍
